version: "3.7"

services:
  database:
    image: postgres
    container_name: pratical_classes
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=practicalclasses
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
